# twitter bootstrap
gem 'bootstrap-sass'
# auto prefixer
gem 'autoprefixer-rails'
# bower dependencies manager for rails
gem 'bower-rails'<% if (includeModernizr) { %>
# modernizr
gem 'modernizr-rails', '~> 2.7.1'<% } %>
# requirejs
gem 'requirejs-rails'<% if (includeButtonCss) { %>
# button sass
gem 'compass-rails'<% } %><% if (includeFontAwesome) { %>
# font awesome
gem 'font-awesome-rails'<% } %><% if (includeMongodb) { %>
# mongoid
gem 'mongoid'<% } %>
# jasmine
group :development, :test do
  gem 'rspec'
  gem "rspec-rails"
  gem 'mailcatcher'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'shoulda-matchers'
  gem 'did_you_mean'
  gem 'guard-rspec'
  gem 'spring-commands-rspec'
  gem 'rb-fsevent' if `uname` =~ /Darwin/
  gem 'shoulda-callback-matchers', '~> 1.0'
  gem 'jasmine'
  gem 'jasmine-rails'
end
group :development do
  gem "better_errors"
  gem "binding_of_caller"
  gem 'meta_request'
end
# rspec
<% if (includeLiveReload) { %>
# livereload using guard server
group :development do
  gem 'guard'
  gem 'guard-livereload', require: false
end<% } %><% if (includeHaml) { %>
# haml template
gem 'haml'<% } %><% if (includeSlim) { %>
# slim template
gem 'slim'<% } %><% if (includeGrape) { %>
# grape api
gem 'grape-entity'
gem 'grape'<% } %><% if (includeRubyRacer) { %>
# embed the V8 Javascript Interpreter into Ruby
gem 'therubyracer', platforms: :ruby<% } %>
